addons/road-generator/road_point.gd, addons/road-generator/road_segment.gd, test/unit/test_match_lanes.gd, test/unit/test_road_point.gd
This update should take care of auto-texturing one-way roads and eliminate unwanted lane lines. All GUT tests passed.
What changed:
ROAD_POINT.GD
Updated road_point.gd to use NO_MARKING texture instead of ONE_WAY in single-lane one-way situations because ONE_WAY resulted in an unwanted line on one side of the lanes where it was used.
Also, updated the "final lane" logic to insure that the "outside" lane texture is NO_MARKING in various one-way multiple lane setups.
ROAD_SEGMENT.GD
Troubleshot an issue where reverse-only lane setups still showed a dotted line on the left side. Updated road_segment.gd "reverse-only" lane matching element result order.
TESTS
Updated both road point and lane matching unit tests.
=> Updated auto-texturing for one-way roads

addons/road-generator/road_point.gd, addons/road-generator/road_segment.gd
Appears to be working when copied into the wheel steal project. The match lane issue was happening when they were properly de-synced but then zero array length, hence failing on reference [0].
Closes https://github.com/TheDuckCow/godot-road-generator/issues/86
=> Workaround for godot empty array synced bug

addons/road-generator/road_point.gd
Before now, road lane widths as well as shoulder widths had to be integer values, when they should have been floats.
All GUT tests pass:
`4 passed 0 failed.  Tests finished in 0.0s`
=> Update export vars so shoulders and lane width are floats.

addons/road-generator/plugin.gd, addons/road-generator/road_network.gd, addons/road-generator/road_segment.gd, project.godot, test/unit/test_match_lanes.gd
See the description in https://github.com/TheDuckCow/godot-road-generator/issues/100, goal here is to avoid repeats in the add UI. It now looks like this, which is desirable:
Closes #100
=> 100-avoid showing repeats in add menu

addons/road-generator/lane_point.gd, addons/road-generator/lane_segment.gd, addons/road-generator/road_network.gd, addons/road-generator/road_point.gd, addons/road-generator/road_segment.gd, project.godot, test/unit/test_match_lanes.gd
In order for AI to function well, we need to have each LaneSegment (which represents a sort of dotted line which AI can follow, including through intersections and lane transitions) connect to its according left-right neighbors, but also a way for the RoadNetwork to do a pass connecting existing LaneSegments to their according same-lane next/prior's.
Closes #47
=> Auto connect LaneSegment ends to neighbors

addons/road-generator/plugin.gd, addons/road-generator/road_lane.gd, addons/road-generator/road_network.gd, addons/road-generator/road_point_gizmo.gd, addons/road-generator/road_segment.gd, project.godot
For easier discoverability and searchability, renamed LaneSegments to RoadLanes. Now, whenever you search for "road" in the add menu, all relevant nodes to this plugin will appear.
All tests pass:
`4 passed 0 failed.  Tests finished in 0.0s`
=> Renamed LaneSegment class and file to RoadLane

addons/road-generator/road_network.gd
Introduces a _dirty flag in the road network, to manage when to trigger rebuilding of all road segments. This was getting to be problematic, as I noticed roads would be regenerated as many as 5x times in a row during scene open (and possible on save, too). Even though each inspector property setter function was initially doing a deferred called to rebuild, they were each triggering it 1x. It now functions on seeing whether it's still "dirty" so they don't overlap.
All 4 tests pass, and no more repeat generations of roads.
There is a potential consequence that this means we can't depend on roads being there in the first frame after _ready, but there's already evidence to believe that this was not reliable anyways. Another PR is focussing on adding necessary signals for that purpose.
Closes …
=> Adding dirty flag to fix duplicate rebuilds on scene open.

addons/road-generator/road_lane.gd, addons/road-generator/road_network.gd, addons/road-generator/road_segment.gd, test/unit/test_match_lanes.gd, test/unit/test_road_network.gd, test/unit/test_road_point.gd
Purpose of this change is to reliably generate a signal when any road segments have been updated, so that downstream listeners can react to the roads (and thus, lanes etc) being updated. It attempts to batch them as much as possible, so one overall rebuilding of all RoadSegments will yield in one signal call referencing all of those roads. 
Not all tests pass right now, due to one recently added test that I thought was initially working but now is not (to with checking rebuild on certain conditions).
Will edit before merging to dev.
```
Totals
Scripts:          3
Passing tests     7
Failing tests     1 # test_on_road_updated_single_segment
Risky tests       0
Pending:          1 # func test_on_road_updated_pt_transform():
Asserts:          49 of 50 passed
```
=> Generate signals on road updated

addons/road-generator/road_network.gd, addons/road-generator/road_point.gd, addons/road-generator/road_segment.gd, test/unit/road_utils.gd, test/unit/test_match_lanes.gd, test/unit/test_road_network.gd, test/unit/test_road_point.gd
Right now, if someone tries to manually update the reference paths of one RoadPoint to another (while auto refresh is on), it won't work at all, because it fails validations for proper connections (as only one road point will connect to the other, and not the reverse as it hasn't been updated yet).
What we should do is, in the on prior/next point init function, do the call to see if we can properly auto-connect to the target roadpoint in question if it has an equally missing next "slot". And thereafter, ensure on making roadpoint updates that the changes of prior on one point are reflected as the next on the other, and vice versa, to make them properly bidirectional lists.
Demo video of the net result of this change:
https://github.com/TheDuckCow/godot-road-generator/assets/2958461/9bb9e25 …
=> Enforce bi-directional RoadPoint connections on path updates

addons/road-generator/plugin.cfg, addons/road-generator/road_network.gd, addons/road-generator/road_segment.gd
All tests pass:
`12 passed 0 failed.  Tests finished in 1.3s`
See the change (going from the old way to the new way). This is essentially taking the best of both worlds (in terms of approaches we've tried so far) by having easing, while also ensuring consistent lane width.
Need to do further checks to ensure the easing is also applied as necessary to the RoadLanes.
=> Persistent lane width and improved easing

addons/road-generator/plugin.gd, addons/road-generator/ui/road_toolbar.tscn, addons/road-generator/ui/road_toolbar_create_menu.gd
12 passed 0 failed.  Tests finished in 1.4s
This makes it more convenient to work with the plugin, especially if you need to disable automatic updates due to large road networks (and thus have "auto refresh" turned off on the RoadNetwork)
=> Add "Refresh roads" and "select network" buttons to Create menu.

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, test/unit/test_road_container.gd
As a stepping stone to allow for the connection of different RoadContainers to other RoadContainers, this PR establishes the concept of "edge RoadPoints".
Whenever adding a new RoadPoint or updating connections of a RoadPoint, the `RoadContainer.update_edges()` function on the given RoadContainer instance will trigger. The result is the update of 5 parallel export var arrays. While it seems excessive, this seems to be the most stable way to ensure bidirectional fetching of data. Basically, these export vars allow the equivalent of a RoadPoint of one container to set its next_pt_init to a RoadPoint on another, but using their corresponding RoadContainers as middlemen. Relevant snippet from the code for more
```gdscript
export(Array, NodePath) var edge_containers # Paths to other …
```
=> Identify container edges

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_toolbar.gd, addons/road-generator/ui/road_toolbar.tscn
This demo video pretty much sums up the current state:
https://twitter.com/TheDuckCow/status/1713319965993169259
- Working toolbar modes for Add- and Dissolve-RoadPoints
- Some more gracefully handling when the RoadContainer has outdated seg_id's
- For add RoadPoint:
- Will attempt to place onto a collision
- If no collision mesh set up under mouse click, then will place the next point in the same plane as the prior selection
- Functional undo/redo, though could be improved
- Dissolve point:
- Not really working quite as hoped yet, but it is using technically a more stable undo/redo mechanism that keeps references in memory
- Thankfully, the "undo" command does work reliably after dissolve, in the meantime users would get about the same and a more stable experience by deleting the node …
=> Establish edit modes

addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_gizmo.gd
We now have nicer defaults for the gutter and initial road magnitudes which correspond to the width of the road. Additionally, we have full resolved https://github.com/TheDuckCow/godot-road-generator/issues/90
See the following small scale:
Only consequence is that when selecting RoadPoints of different lane widths, all widgets change at the same moment. But, the one actively being selected is always as desired.
=> Improved defaults and size agnostic widget editing

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_toolbar.tscn, addons/road-generator/ui/road_toolbar_create_menu.gd
Includes necessary utility function to work around the autofix cyclic functionality that was getting in the way.
Still in draft due to existing bug, see comment below.
=> Establishing Connection tools

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/nodes/road_segment.gd
Work in progress, to ensure users can connect roads RoadPoints, even if the face opposing directions. This is important as someone could be joining two different chains of roads that have many points and all face the wrong way compared to another stretch of road.
RoadPoints are ideally agnostic of direction, although a given RoadPoint will "own" one or more RoadSegment children. So in the event two roadpoints are facing each other (ie they both claim they are each others' "Next RoadPoint" for instance), one of them will inherently take ownership of the connection between them. We need to make sure to do this in a reliable, deterministic way.
=> Eliminating duplicate segments with changes in connection direction.

.gitignore, CONTRIBUTING.md, release.sh, run_tests.sh
This included script makes it easier to run test automatically on the command line. This is a potential stepping stone to eventually supporting test-running via github actions. Included script is for OSX and linux only (only tested on OSX though)
=> Added instructions and script for command line testing

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_toolbar.gd, addons/road-generator/ui/road_toolbar_create_menu.gd, test/unit/test_road_container.gd, test/unit/test_road_point.gd
Until now, users have not been able to make connections between two different RoadContainers with the interactive tool (and doing so manually with paths would create unexpected artifacts). In this branch, we first start to allow for connections. This is a stepping stone to fully support generalize custom prefab scene creation while retaining traffic AI guides (RoadLanes).
Edited at time of being review-ready:
- When connecting RoadContainers, we detect if the two highlighted RoadPoints (on each respective RoadContainer) are already overlapping in 3D space
- If yes, directly connect them through export var chaining.
- If no, create a new roadpoint at the right position, then connect that _new_ roadpoint to the new container.
- This new roadpoint is added as a child of the container of the …
=> Establish connections between RoadContainers

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/nodes/road_segment.gd, addons/road-generator/plugin.gd
Adds auto checks to see if there are invalid connections or positions of RoadPoints advertised to be connected to roadpoints on other containers.
Additionally, creates an auto-snap function which will be called when pressing the physical button to Refresh Roads. As a consequence, other references which were more lazily calling rebuild segments with clear existing = true, were set to rebuild using clear existing = false or perform the necessary lower level function. This actually increases the performance of some actions, such as toggling RoadLane visibility.
This branch also moves RoadLanes to be direct children of RoadPoints (instead of children of RoadSegments), to allow for a future where we can directly expose them in the editor.
Also address in part, but not whole, the issue of [a …
=> Auto disconnect containers

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_intersection.gd, addons/road-generator/nodes/road_lane.gd, addons/road-generator/nodes/road_manager.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/nodes/road_segment.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_edit.gd, addons/road-generator/ui/road_point_gizmo.gd, addons/road-generator/ui/road_point_panel.gd, addons/road-generator/ui/road_toolbar.gd, addons/road-generator/ui/road_toolbar_create_menu.gd, test/unit/test_road_point.gd
This is based on going through some manual updates after using the auto conversion tool. More changes could be made to help improve this.
Note: this is NOT representing a conversion to godot 4 itself, just making it easier. In the event we actually decide to properly support godot 4 and godot 3 in parallel, these changes will make it much more manageable.
=> Improve auto and manual conversion to godot 4

addons/road-generator/nodes/road_segment.gd
Hey @TheDuckCow, there is still ongoing work in this branch. But, here is the incremental change we talked about in order to resolve some of the RoadLane wonkiness.
The simplest test case was to create a 2x2 Road, select both RoadPoints, and rotate 45°. The road geometry looked fine. But, the RoadLanes zigzagged across the road.
What this change does: When adding new RoadLanes, it translates the Curve Point In and Out values from RoadSegment Local Space to Global Space. Then, from Global to RoadPoint/RoadLane Local Space.
An alternative workaround was to add the RoadLanes as children of the RoadSegment instead of the RoadPoint. That fixed the wonkiness. But, it broke the AI logic that expected to find the RoadLanes as children of the RoadPoint.
=> 46 update lanesegments

addons/road-generator/nodes/road_container.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_panel.gd, demo/test_scene.gd, demo/test_scene.tscn
Fixing the primary cause of startup console errors if multiple scenes open.
Before this change we could get many errors on startup if we had multiple startup scenes auto-opened with road generator usage. For any scene _other_ that the one which is set to active, we'd get these slew of errors:
```
Cannot get path of node as it is not in a scene tree.
scene/3d/spatial.cpp:407 - Condition "!is_inside_tree()" is true. Returned: Transform()
```
These were hard to debug initially since it gives no culprit line outputs, and may be an issue very unique to the editor. But the scene check is a safer one anyways for rebuild segments worth keeping for production builds too. Need to test exported project still work with this.
=> Fix not in tree startup errors

addons/road-generator/nodes/road_segment.gd
Curve offsets are nicely drawn. However, something must be done about Lane Transitions. They plot perfectly fine. But, the IDE freezes when the "+Next RoadPoint" and "+Prior RoadPoint" buttons are used. Said buttons don't freeze the IDE when there are no Lane Transitions.
=> RoadLane offset approx algorithm

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_edit.gd, addons/road-generator/ui/road_point_gizmo.gd, addons/road-generator/ui/road_point_panel.gd, addons/road-generator/ui/road_point_panel.tscn
For all 3D widget as well as the relevant RoadPoint's Inspector Panel buttons, we now can hold shift when performing/completing actions for different effects. As implemented right now, holding shift lets you:
- Mirror the prior/next magnitude when dragging the orange gizmo widget
- Add or remove a lane to _all_ RoadPoints on the same RoadContainer after pressing the button or dragging the blue gizmo
- Select the first or last (connected) RoadPoint within the same container via the RoadPoint panel
Would be great to also add a "copy all attributes" button too, to make it easy to tweak one RoadPoint and copy it over to the others.
=> Added shift-for-bulk operations and copy/paste attributes

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_segment.gd, test/unit/test_match_lanes.gd
This was an issue if two connected RoadPoints were both pointed towards each other or away from each other while being directly connected.
This does not yet resolve related issues with the RoadLane construction, though there are some improvements in making them reuse existing roadlanes.
Added new test for this scenario, now passing. Edit: Updated again now and still all passing
Closes #136
=> Resolved texture assignment for segments between flipped RoadPoints

addons/road-generator/nodes/road_manager.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/nodes/road_segment.gd
I find that applying a density of 4 (which reads "1 mesh loop every 4 meters") is a better default than our current 2x, which has twice as many loop cuts. At 4m with the default lane width also of 4m, it makes for nearly square but long rectangles.
at density=2 (previewws)
at density=4 (new)
Of course, really sharp turns will still look a little low poly on the outside edge. And turns with roads with a higher number of lanes will also tend to look courser. But I do feel this is still a good general default starting place. In wheel steal game, for instance, we have a density of 3 but if not for the discontinuity of CSG mesh creation, would push it higher.
=> Updating default density to 1 loop for 4m for improved performance

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_segment.gd, test/unit/test_road_container.gd
Closes #176 by providing options to assign the generated static colliders. 
Test results:
`24 passed 0 failed.  Tests finished in 1.8s`
=> Added collider to group with assigned meta for easier script fetching

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_manager.gd, addons/road-generator/plugin.gd, demo/performance_stress_test.gd, demo/performance_stress_test.tscn, demo/simple_demo.tscn, test/unit/test_road_container.gd
Reworked the container start up procedure to have avoid doing a deferred geometry generation call in some cases. Now, instead of depending on the auto-calling of deferred loading via export var property setget callbacks, we now avoid doing generation during getting ready.
Added a stress test file which can be used for speed checking of generation in the future, as well as updated unittests to reinforce pre-existing behavior of emitting the `on_road_updated` signal on RoadContainers even if no road segments are generated (such as having no children, or if clear_existing=false while all road segmetns already have initial meshes in place).
Also improved in-code documentation for export vars.
The `RoadManager.rebuild_all_containers` function is no longer a deferred call but will rather block …
=> More responsive UI with some rebuilds prevented

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_point.gd, test/unit/test_road_container.gd
We somewhat recently added the concept of "terminated" RoadPoints, which are meant to represent RoadPoints which are not connected on one or both sides, but are not meant to be considered as open edges from the standpoint of the parent RoadContainer (and thus, not available for connections across RoadContainers).
This change actually ensures the edge list doesn't include these RoadPoints, to avoid downstream checks for "terminated == true", and adds a set-getter to ensure the RoadContainers edge list is always up to date in the editor.
=> Remove terminating RPs from container edge list

addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd
The Dissolve and Delete RoadPoint funciton in the toolbar was largely broken up until now. With this PR, the undo and redo stack is working very nicely, without any errors in the console (except in some edge cases where it seems some internals call transform, but only yielding "not in tree" errors which don't actually impact the output).
See demo here, showing this in detail:
https://github.com/user-attachments/assets/47f9540c-534e-4fa6-a6ff-658a89e8fac7
=> Fix dissolve and delete roadpoints undo redo

addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_edit.gd
Consolidate to use the same method as in the click-to-add code. The actual do/undo references there could be improved too, but seems to work stably in the meantime.
This also includes a change to improve the automatic in/out magnitude handles for the new and initially selected RoadPoint, making for more natural graceful turns (but still without modifying the prior curves, so the handles _can_ become asymmetric).
Closes #84
=> Improved undo/redo of RoadPoint edit panel's add next/prior rp

addons/road-generator/nodes/road_container.gd, addons/road-generator/plugin.gd
Now we have _much_ fewer error printouts when working with the plugin in general, thanks to being a bit more mindful of when calling the update edges routine, and taking care when we actually add the node to the scene.
Before:
With these new changes 🎉 
The remaining (4.x only) issue of undo/redo counts is captured in https://github.com/TheDuckCow/godot-road-generator/issues/193 and won't be solved in this v0.5.1 release
=> 4.x Reducing console errors on adding RoadPoint via menu or click

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_segment.gd
Resolves #196  where curve edges were not automatically being generated due the resource not auto-creating as it does in godot 3.5x
=> Auto generate new curve resources if needed

addons/road-generator/plugin.gd
Fixes issues mentioned in issue #193
=> Fixing undo redo stack issues in godot4

addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_edit.gd
Gets around an issue which could cause custom or other resources to not properly be editable, due to over-scoped editor handler function.
Resolves #195
=> Applying discovered fix to make resources editable and avoid errors

addons/road-generator/nodes/road_segment.gd, demo/procedural_generator/procedural_generator.gd
Used updated procedural-generation demo to test
The main unsupported case I was working on was when one direction of the road expands while another shrinks
as an example for a problematic case:
R,R,R,F,F <-> R,R,F,F,F
from what I see, the algorithm was trying to calculate which road point is wider (while both are the same)
I mostly worked on godot4 branch, but checked that it works on dev branch as well
I think its related to https://github.com/TheDuckCow/godot-road-generator/issues/171https://github.com/TheDuckCow/godot-road-generator/issues/171
=> [171] Fixed incorrect connection of road lanes

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_lane.gd, addons/road-generator/nodes/road_lane_agent.gd, addons/road-generator/nodes/road_segment.gd
This code is my first attempt of a small refactoring in the project, so please consider it as a proposal and invitation to discussion based on the working code :)
In my mind it make sense just from abstraction point of view when working with lanes - so you wouldn't have to think about segment order/direction. instead you're having "natural" order where bigger lane offsets and next means forward, lower lane offset and prior Road lane means backward. Also left/right lane links already in "natural" order for the road lanes so I think this proposal makes it more consistent
"reverse flag" still left to ease connection search and GUI purposes, but not for moving along the RoadLane list
Essentially  this proposal moves complexity from agent, which doesn't have to consider whether it moves on …
=> Proposal: make reversed lanes continuous

addons/road-generator/nodes/road_point.gd, addons/road-generator/plugin.gd, addons/road-generator/ui/road_point_edit.gd, addons/road-generator/ui/road_point_panel.gd, addons/road-generator/ui/road_point_panel.tscn, demo/intersections/intersection_demo.tscn
There are some cases where it's helpful to rotate a RoadPoint 180º around its y-axis to get all RoadPoints to point along the same direction. In the future, this may be performed automatically or instead performed on an entire RoadContainer at once. However until then, this tool to manually flip individual RoadPoints will suffice. 
The goal of this operation is that visually for the user, the RoadPoint will appear entirely unchanged - meaning after the 180º rotation occurs, any asymmetries will be mirrored. For instance the forward bezier magnitude size is flipped with the reverse, the left-to-right lane directions will also be flipped around.
Demo of the flip tool can be seen here: notice how the Z-direction of the RoadPoint is flipped, but the mesh otherwise stays the same there (in …
=> Added roadpoint flip tool to assist with normalization

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_manager.gd, addons/road-generator/nodes/road_segment.gd
Resolves #203 and #217 to create control over collision layers/masks and exposing physicals material. This change is backwards compatible as no pre-existing public variables have been renamed.
This PR also extends several export vars on the RoadContainer class into the RoadManager class. This way, a RoadContainer can be set up to override the RoadManager if something special is needed, but by default properties will extend from the RoadManager directly. For most users, this is ideal since they likely want to use the same settings for all RoadContainers. The settings that are newly available on the RoadManager include:
- material_resource
- physics_material
- collider_group_name
- collider_meta_name
- collision_layer
- collision_mask
- road_lanes
Also organizes the export vars for both …
=> Collision layers and physics slot

addons/road-generator/nodes/road_container.gd, addons/road-generator/nodes/road_intersection.gd, addons/road-generator/nodes/road_lane.gd, addons/road-generator/nodes/road_lane_agent.gd, addons/road-generator/nodes/road_manager.gd, addons/road-generator/nodes/road_point.gd, addons/road-generator/nodes/road_segment.gd, demo/intersections/intersection_demo.tscn
Fixed spacing so that documentation actually appears in the inspector panel itself.
Where appropriate, re-ordered some classes to be more consistent with the official godot styleguide.
Sample of how it looks when opening the local documentation search in Godot 4.3:
And when hovering over tooltips in the inspector panel:
=> Support in-app documentation and improved export grouping for addon nodes

addons/road-generator/nodes/road_point.gd, addons/road-generator/nodes/road_segment.gd, addons/road-generator/ui/road_point_edit.gd, addons/road-generator/ui/road_point_gizmo.gd, demo/procedural_generator/ProceduralGenerator.tscn
Create Road Point alignment property
Modes supported:
1. road point is in the center of the road (original)
2. road point is on double yellow line. for one-way roads new alignment is on the leftmost lane
make alignment attribute visible and registered for copy (either in plugin GUI and RoadPoint copy method)
update lanes, edges and geometry to use offsets, according to the alignment property (including mixed alignment in segment's road points)
update custom gui handles for lanes to show arrows with respect to alignment attribute
related to https://github.com/TheDuckCow/godot-road-generator/issues/229
From my work, I see that it has to be a road-point centered feature, as it makes no sense if there are no FORWARD or no REVERSE lanes, makes the road left or right aligned and demanding that …
=> Add double yellow alignment option

addons/road-generator/ui/road_point_edit.gd, addons/road-generator/ui/road_point_panel.gd, addons/road-generator/ui/road_point_panel.tscn
Resolves #234 by disabling the add previous/next button from the RoadPoint inspector panel custom drawing, which was causing potential crashing issues.
This also updates some tooltips and labels to be a bit more natural and improved spacing/wrapping. This additionally puts the panel squarely underneath the RoadPoint panel section itself, instead of at the top of the inspector panel.
=> Disable Add Next/Previous RP to avoid crashing, panel re-organization

addons/road-generator/plugin.gd, addons/road-generator/ui/road_container_edit.gd, addons/road-generator/ui/road_container_panel.gd, addons/road-generator/ui/road_container_panel.tscn, addons/road-generator/ui/road_toolbar_create_menu.gd
We now have an Export RoadContainer gLTF button in the editor, both in the road toolbar dropdown in the 3D editor, and in the inspector panel when a RoadContainer is selected. This allows users to export the given RoadContainer and all its children to a glb/gltf file on disk. Additionally, there is an option that allows for auto instancing the exported glb/gltf file into the scene while also turning off the "create geo" flag on the RoadContainer, making it one step easier to customize the geo for a given scene seutp.
Closes #207
Demo here, showing the "instance after export" option, showing that it'll bring the exported roads exactly into place:
https://github.com/user-attachments/assets/fbda1933-1e9a-45d6-a62a-18fca581fc58
=> Add gLTF exporter for RoadContainers

addons/road-generator/nodes/road_segment.gd
Made formatting more verbose to make it easier to see what needed changes.
Before this change, we were seeing an issue like you see here, something I discovered while working on the gLTF exporter. Not sure when it was introduced, but definitely an important one to fix!
=> Fixing overlapping shoulder geo on the right side

addons/road-generator/plugin.gd
Prevented placing RoadPoints facing away from you in the camera for some reason
=> Fix bad .dot call when placing new RoadPoints

addons/road-generator/nodes/road_container.gd
Hey there, small PR that adds the parent name to the warning where a RoadPoint is not connected to anything.
When refreshing my roads earlier, I had a problem of finding the RoadPoint the warning spoke about. When using the presets, You usually end up with a structure similar to:
* RoadManager
* Road_001
* RP_001
* RP_002
* Road_002
* RP_001
* RP_002
* RP_003
* Road_003
* RP_001
* RP_002
The warning displays as:
```
WARNING: core/variant/variant_utility.cpp:1034 - Road point RP_001 not connected to anything yet
```
Which means you have to check every RP_001 in the project. This PR changes the print for this warning to:
```
WARNING: core/variant/variant_utility.cpp:1034 - Road point Road_002/RP_001 not connected to anything yet
```
=> Add parent name to RoadPoint not connected warning

addons/road-generator/connectors/terrain3d_road_connector.gd
This PR adds a lightweight integration between the Road Generator and Terrain3D plugins. It simply requires on public signals or class function methods in order to 
We are actively looking for feedback, but regardless this will be included in the next Road Generator release
- Test it by adding the simple Node into your scene with the script this PR adds, and connect the export var to the corresponding nodes (you should already have a terrain3d and RoadManager object in your scene)
- Play around with the other export like edge margin and edge falloff
- Works when drawing new roads, changing lane counts, and moving roads around
- Made to work with the latest v1.0 version of Terrain3D, older versions of Terrain3D won't work due to a slight API change
- Currently no way to mark sections of …
=> Add road connector to flatten Terrain3D

addons/road-generator/nodes/road_segment.gd
This introduces easing to the calculation for the orientation of the lateral direction of the road for any given offset of the road, which previously was purely linear. A previous PR also adjusted the easing param from -2.0 to -1.4 to better fit more common alignments of the edge curves generated.
I thought about creating export vars to change the easing factor, but I'm not sure this exact behavior will continue existing in the future - especially given it feels somewhat unnatural that the scaling of the magnitude handles doesn't affect the easing falloff (for the road width, at least).
Visual representing the before (left) after (right):
=> Ease lateral road orientation

addons/road-generator/nodes/road_segment.gd
I have a lot of road points that are named i.e. `RP_002` so when I ran into this warning, I wasn't sure which road container to look at to fix it. Including the parent here makes it easier to debug.
=> Include parent node when printing error about mismatched lanes
